path:
  ckpt_path: "./output/ckpt/LJSpeech_64"
  log_path: "./output/log/LJSpeech_64"
  result_path: "./output/result/LJSpeech_64"
optimizer:
  batch_size: 64
  betas: [0.9, 0.98]
  eps: 0.000000001
  weight_decay: 0.0
  grad_clip_thresh: 1.0
  grad_acc_step: 1
  warm_up_step: 1000
  anneal_steps: [75000, 100000, 125000]
  anneal_rate: 0.3
step:
  total_step: 225000
  # total_step: 150
  log_step: 100
  synth_step: 2000
  val_step: 500
  save_step: 2000
